import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import Navbar from "./_components/Navbar";
import "@/app/_styles/globals.css";

const manrope = Manrope({
  weight: "600",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className}  antialiased w-screen h-dvh`}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}

// UPDATE THE FONTS - FIND NICE FONT
